### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by Klaster1** [mortenn/BrowserPicker#93]
How to reproduce:
1. Install the [v2.0-beta3](https://github.com/mortenn/BrowserPicker/releases/tag/v2.0-beta3).
2. Open BrowserPicker from the Windows start menu.
3. Enable the "Default \ Always user specified browser...".
4. Click done.
5. Open BrowserPicker.
6. Disable the setting, click done.
7. Open BrowserPicker again.

Expected:
The setting is disabled.

Observed:
The setting is on.

Notes:
Removing browsers from the browser list exhibits the same behavior. Editing the redirect list works as expected.

**Comment by mortenn** [comment]
Hi, did you try beta 3.1?

**Comment by Klaster1** [comment]
The 3.1 does not fix the issue.

**Comment by coromd** [comment]
I am having the same issue as well on beta 3.1
![notepad++_bsO3bo1yGq](https://github.com/mortenn/BrowserPicker/assets/11288368/31621447-15f9-403c-b2c1-f585ce08c6eb)

**Comment by mortenn** [comment]
Hello, I've just rewritten the configuration part of the app and upgraded it to .NET 8, if you would be so kind as to give [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8495248070/artifacts/1372113556) a try, that'd be great!

**Comment by mortenn** [comment]
there were some additional bugs which have been fixed in [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8499547340/artifacts/1372850785)

**Comment by mortenn** [comment]
I have released v2.0.1 prerelease which hopefully works now :)

**Comment by mortenn** [comment]
This should be resolved in 2.0.1/2.0.2, let me know if the problem persists.

**Comment by Deathbot64** [comment]
On the newest version I am still seeing some issues with settings now fully saving. When No Default is configured matching the url is one setting that will not save.

**Comment by mortenn** [comment]
Could you please record a video of the issue and open a new issue for that one?

**Comment by Deathbot64** [comment]
I found a workaround (I think anyways) to get it working. I uninstalled 2.0.6. Then installed 2.0.1, updated the setting there which worked. Then updated to 2.0.6 and now the setting seems to save even after changing browser. But I havent tried to disable it again yet. I also do not see a key in the registry settings for this setting.

**Comment by mortenn** [comment]
I am not sure which setting you are referring to

**Comment by Deathbot64** [comment]
![Screenshot 2024-04-04 181443](https://github.com/mortenn/BrowserPicker/assets/74361687/10c01206-50f5-44c6-a8ad-4ca378ccbade)
This one

**Comment by mortenn** [comment]
Ah, I see.
I wasn't really expecting anyone to use that one without any defaults, as doing so basically just makes BrowserPicker not do anything other than launching your one browser.

That setting gets saved as the (default) value in the registry
![image](https://github.com/mortenn/BrowserPicker/assets/640095/7bac3cf9-5a16-4a10-a66f-a7dc2346b7ac)
